# GitHub Actions workflow to build Android APK and iOS app
# This workflow runs on push and pull request events to main branch

name: Build Android and iOS Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fish-catch-leaderboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './fish-catch-leaderboard/package-lock.json'
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
      - name: Install dependencies
        run: npm ci
        
      - name: Make gradlew executable
        run: chmod +x android/gradlew
        
      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: fish-catch-leaderboard/android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./fish-catch-leaderboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace fish-catch-leaderboard.xcworkspace -scheme fish-catch-leaderboard -sdk iphonesimulator -configuration Debug build
      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: fish-catch-leaderboard/ios/build
