name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: fish-catch-leaderboard/package.json
      - name: Install dependencies
        working-directory: fish-catch-leaderboard
        run: npm ci || npm install
      - name: Run tests
        working-directory: fish-catch-leaderboard
        run: npm test -- --watchAll=false
        env:
          CI: true
      - name: Build
        working-directory: fish-catch-leaderboard
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: fish-catch-leaderboard/build
          publish_branch: gh-pages
          force_orphan: true
